### ISSUE TITLE
Update docs to be explicit for odd setups

### ISSUE THREAD

**Issue by bzmwillemsen** [podio/requirejs-react-jsx#4]
I have a bit of an odd setup and I had to do define the following in my `requirejs.conf`

``` javascript
    'react': 'bower_components/react/react-with-addons',
    'JSXTransformer': 'bower_components/react/JSXTransformer',
    'jsx': 'bower_components/requirejs-react-jsx/jsx',
    'text': 'bower_components/requirejs-text/text'
```

the `text` module is required my `requirejs-react-jsx` and with an odd setup it doesn't find it magically.

**Comment by alexwasner** [comment]
I had a similar issue that was resolved with @bzmwillemsen fix

**Comment by srn** [comment]
Thanks guys, I've added the `text` plugin in the `readme.md`.
