### ISSUE TITLE
Difference between client-side and build compilation

### ISSUE THREAD

**Issue by kirill-konshin** [podio/requirejs-react-jsx#9]
Client side allows syntax:

```js
React.createClass({
  render(){ // no ":function" between name and ()
    // ...
  }
});
```

During the build this causes an error.

**Comment by srn** [comment]
This should work if you remember to include this in your `requirejs.config`:

```js
jsx: {
  transformOptions: {
    harmony: true
  }
}
```

**Comment by kirill-konshin** [comment]
It probably should be enabled by default to match with client-side default settings.

Second, usually module configurations are stored as `config` property of object supplied to `requirejs.config()`:

```js
requirejs.config({
  config: { // note this additional config property
    jsx: {...}
  }
});
```

From the plugin it should be accessed as:

```js
// was
var options = config.jsx && config.jsx.options.transformOptions || {}; // btw this is still not safe enough
// proposed
var options = config.config && config.config.jsx && config.config.jsx.options.transformOptions || {};
```

**Comment by kirill-konshin** [comment]
http://requirejs.org/docs/api.html#config-moduleconfig Link to documentation about `config` section.

**Comment by srn** [comment]
You're right. Feel free to create a PR with the proposed changes :+1:

**Comment by kirill-konshin** [comment]
Here you go: PR https://github.com/podio/requirejs-react-jsx/pull/10

**Comment by kirill-konshin** [comment]
BUMP!

**Comment by kirill-konshin** [comment]
I've found a small issue + I've added a safer check. This could be 0.14.1 :) https://github.com/podio/requirejs-react-jsx/pull/11

**Comment by Munter** [comment]
This seems to be dealt with now. Thanks for the contributions!

**Comment by kirill-konshin** [comment]
Confirmed.
